[package]
name = "substrate-subxt-client"
version = "0.7.0"
authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
repository = "https://github.com/paritytech/substrate-subxt"
documentation = "https://docs.rs/substrate-subxt-client"
homepage = "https://www.parity.io/"
description = "Embed a substrate node into your subxt application."
keywords = ["parity", "substrate", "blockchain"]

[dependencies]
async-std = "1.8.0"
futures = { version = "0.3.9", features = ["compat"], package = "futures" }
futures01 = { package = "futures", version = "0.1.29" }
jsonrpsee-types = "0.2.0"
log = "0.4.13"
serde_json = "1.0.61"
thiserror = "1.0.23"

sc-client-db = { package = "sc-client-db", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { package = "sc-network", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sc-service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[target.'cfg(target_arch="x86_64")'.dependencies]
sc-service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false, features = ["wasmtime"] }

[dev-dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
env_logger = "0.8.2"
tempdir = "0.3.7"
